### ISSUE TITLE
Empty file remains when I don't especially want it to

### ISSUE THREAD

**Issue by cefyr** [kalpana-org/kalpana#78]
When I open kalpana with dmenu or something (not in terminal), sometimes I don't actually want the empty file because I'm on my way to opening something else. But because the empty file feels modified and I have "open file in new window" enabled, the empty file remains and needs to be q!-closed. 

If a file has neither name nor wordcount, could it disappear quietly perhaps when I go on to bigger and better things?

**Comment by nycz** [comment]
yep this is fixed
